name: Build & Deploy Dev

on:
  push:
    branches:
      - develop

jobs:
  build-container:
    name: Build and push container
    secrets: inherit
    uses: EpayVNTech/workflow/.github/workflows/container_build_latest.yaml@develop
#name: Build & Deploy Dev
#
#on:
#  push:
#    branches: [ develop ]
#
#jobs:
#  build-container:
#    name: Build and Publish to Azure Container Registry
#    runs-on: ubuntu-latest
#    env:
#      SVC_NAME: monex-homepage-site-svc
#      ACR_NAME: ${{ secrets.CONTAINER_REGISTRY_HOST }}
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Login to Container Registry
#        uses: azure/docker-login@v1
#        with:
#          login-server: ${{ secrets.CONTAINER_REGISTRY_HOST }}
#          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
#          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
#
#      - name: Build Container image
#        run: docker build -t ${ACR_NAME}/${SVC_NAME}:latest .
#
#      - name: Publish Docker image
#        run: docker push ${ACR_NAME}/${SVC_NAME}:latest
